set:
  name: Set
  description: Set the schedule.
  target:
    entity:
      domain: binary_sensor
      integration: daily_schedule
  fields:
    schedule:
      name: Schedule
      description: List of the ON time ranges.
      required: true
      selector:
        object:
      example:
        - from: "03:00:00"
          to: "04:30:00"
        - from: "14:45:00"
          to: "19:00:00"
